# Ex1 - Filtering and Sorting Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

### Step 3. Assign it to a variable called chipo.

In [2]:
file_path = "chipotle.tsv"

chipo = pd.read_csv(file_path, sep="\t")

### Step 4. How many products cost more than $10.00?

In [3]:
chipo["item_price"] = chipo["item_price"].apply(lambda price: float(price[1:]))
chipo[chipo["item_price"] > 10].shape[0]

1130

### Step 5. What is the price of each item? 
###### print a data frame with only three columns item_name choice_description and product_price

In [4]:
chipo["product_price"] = chipo["item_price"] / chipo["quantity"]

In [5]:
chipo[["item_name", "choice_description", "product_price"]].drop_duplicates().sort_values(by="item_name")

,item_name,choice_description,product_price
357,6 Pack Soft Drink,[Coke],6.49
3141,6 Pack Soft Drink,[Lemonade],6.49
721,6 Pack Soft Drink,[Nestea],6.49
298,6 Pack Soft Drink,[Sprite],6.49
341,6 Pack Soft Drink,[Diet Coke],6.49
...,...,...,...
781,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Black Beans, Cheese, Sou...",8.75
2851,Veggie Soft Tacos,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",8.49
1395,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",8.49
3889,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",8.49
1699,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25

### Step 6. Sort by the name of the item

In [6]:
chipo.sort_values(by="item_name")

,order_id,quantity,item_name,choice_description,item_price,product_price
3389,1360,2,6 Pack Soft Drink,[Diet Coke],12.98,6.49
341,148,1,6 Pack Soft Drink,[Diet Coke],6.49,6.49
1849,749,1,6 Pack Soft Drink,[Coke],6.49,6.49
1860,754,1,6 Pack Soft Drink,[Diet Coke],6.49,6.49
2713,1076,1,6 Pack Soft Drink,[Coke],6.49,6.49
...,...,...,...,...,...,...
2384,948,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75,8.75
781,322,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Black Beans, Cheese, Sou...",8.75,8.75
2851,1132,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",8.49,8.49
1699,688,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25,11.25
1395,567,1,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",8.49,8.49

### Step 7. What was the quantity of the most expensive item ordered?

In [7]:
chipo.sort_values(by="item_price", ascending=False).head(1)[["item_name", "quantity", "item_price"]]

                         item_name  quantity  item_price
3598  Chips and Fresh Tomato Salsa        15       44.25

### Step 8. How many times was a Veggie Salad Bowl ordered?

In [8]:
veggie_salad_bowl = chipo[chipo["item_name"] == "Veggie Salad Bowl"]
veggie_salad_bowl["quantity"].sum()

np.int64(18)

### Step 9. How many times did someone order more than one Canned Soda?

In [9]:
canned_soda = chipo[chipo["item_name"] == "Canned Soda"]
canned_soda[canned_soda["quantity"] > 1].shape[0]

20